services:
  db:
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  minio:
    environment:
      MINIO_SERVER_URL: "https://${MAIN_DOMAIN}/s3"
    volumes:
      - minio_data_prod:/data

  backend:
    env_file:
      - .env

  nginx:
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_PORT: ${NGINX_PORT}
      RATE_LIMIT_ENABLED: ${RATE_LIMIT_ENABLED}
      SSL_ENABLED: ${SSL_ENABLED}
      SSL_CERT_NAME: ${SSL_CERT_NAME}
      SSL_KEY_NAME: ${SSL_KEY_NAME}
      HSTS_MAX_AGE: ${HSTS_MAX_AGE}

volumes:
  postgres_data_prod:
  minio_data_prod: