services:
  db:
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
  
  minio:
    volumes:
      - minio_data_local:/data
  
  backend:
    env_file:
      - ".env.local"

  nginx:
    ports:
      - "5000:80"
    environment:
      NGINX_PORT: ${NGINX_PORT}
      RATE_LIMIT_ENABLED: ${RATE_LIMIT_ENABLED}
      SSL_ENABLED: ${SSL_ENABLED}
      HSTS_MAX_AGE: ${HSTS_MAX_AGE}

volumes:
  postgres_data_local:
  minio_data_local: