services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  seaweed-master:
    image: chrislusf/seaweedfs:4.33
    restart: unless-stopped
    stop_grace_period: 30s
    command: "master -port=9333 -mdir=/data"
    networks:
      - seaweed_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://seaweed-master:9333/cluster/healthz"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s

  seaweed-volume:
    image: chrislusf/seaweedfs:4.33
    restart: unless-stopped
    stop_grace_period: 30s
    command: "volume -mserver=seaweed-master:9333 -port=8080 -dir=/data -max=1"
    networks:
      - seaweed_net
    depends_on:
      seaweed-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://seaweed-volume:8080/healthz"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s

  seaweed-filer:
    image: chrislusf/seaweedfs:4.33
    restart: unless-stopped
    stop_grace_period: 30s
    command: "filer -master=seaweed-master:9333 -port=${SEAWEEDFS_FILER_PORT}"
    networks:
      - seaweed_net
    depends_on:
      seaweed-master:
        condition: service_healthy
      seaweed-volume:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://seaweed-filer:${SEAWEEDFS_FILER_PORT}/"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s

  seaweed-s3:
    image: chrislusf/seaweedfs:4.33
    restart: unless-stopped
    stop_grace_period: 30s
    environment:
      AWS_ACCESS_KEY_ID: ${SEAWEEDFS_S3_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${SEAWEEDFS_S3_SECRET_KEY}
    command: "s3 -filer=seaweed-filer:${SEAWEEDFS_FILER_PORT} -port=${SEAWEEDFS_S3_PORT}"
    networks:
      - seaweed_net
      - seaweed_public_net
    depends_on:
      seaweed-filer:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pgrep", "weed"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s

  db-prepare:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: final
    env_file:
      - .env.local
    networks:
      - db_net
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node dist/src/cli.js seed admin -e ${SEED_ADMIN_EMAIL} -p ${SEED_ADMIN_PASSWORD} || true"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: final
    restart: unless-stopped
    env_file:
      - .env.local
    networks:
      - backend_net
      - db_net
      - seaweed_backend_net
    depends_on:
      db:
        condition: service_healthy
      db-prepare:
        condition: service_completed_successfully

  # frontend-web placeholder

  frontend-admin:
    build:
      context: ./frontend/admin
      dockerfile: Dockerfile
      target: final
    restart: unless-stopped
    networks:
      - frontend_admin_net

  nginx:
    image: nginx:1.31
    restart: always
    environment:
      # NGINX config
      NGINX_HOST: ${APP_MAIN_DOMAIN}
      NGINX_PORT: ${NGINX_PORT}
      # SSL
      SSL_ENABLED: ${SSL_ENABLED}
      SSL_CERT_NAME: ${SSL_CERT_NAME}
      SSL_KEY_NAME: ${SSL_KEY_NAME}
      HSTS_MAX_AGE: ${HSTS_MAX_AGE}
      # Services
      SEAWEEDFS_HOST: seaweed-s3:${SEAWEEDFS_S3_PORT}
      SEAWEEDFS_SLUG: ${SEAWEEDFS_FILER_SLUG}
      BACKEND_API_HOST: backend:${API_PORT}
      BACKEND_SLUG: ${BACKEND_SLUG}
      FRONTEND_ADMIN_HOST: frontend-admin:${FRONTEND_ADMIN_PORT}
      FRONTEND_ADMIN_SLUG: ${FRONTEND_ADMIN_SLUG}
      FRONTEND_WEB_HOST: frontend-web:${FRONTEND_WEB_PORT}
      FRONTEND_WEB_SLUG: ${FRONTEND_WEB_SLUG}
      PUBLIC_ASSETS_SLUG: ${PUBLIC_ASSETS_SLUG}
      ADMIN_UPLOAD_FILE_MAX_SIZE: ${ADMIN_UPLOAD_FILE_MAX_SIZE_MB}M
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infrastructure/nginx/templates:/etc/nginx/templates:ro
      - ./infrastructure/nginx/includes:/etc/nginx/includes:ro
      - ./infrastructure/nginx/error-sites:/usr/share/nginx/html/errors:ro
      - ./infrastructure/nginx/ssl/certificates:/etc/nginx/ssl/certificates:ro
      - ./infrastructure/nginx/public-assets:/usr/share/nginx/html/public-assets:ro
    networks:
      - backend_net
      - frontend_admin_net
      - seaweed_public_net
    depends_on:
      backend:
        condition: service_started
      frontend-admin:
        condition: service_started
      seaweed-s3:
        condition: service_healthy
        

networks:
  db_net:
  seaweed_net:
  seaweed_backend_net:
  seaweed_public_net:
  backend_net:
  frontend_main_net:
  frontend_admin_net: