name: CI Pipeline

on:
  push:
    branches: [main, develop, demo]
  pull_request:
    branches: [main, develop, demo]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v7.0.0
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/admin/package-lock.json

      - name: Install dependencies
        run: npm run install

      - name: Run unit tests
        run: npm run test

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v7.0.0
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm run install:backend

      - name: Create .env file
        run: echo "${{secrets.ENV_TEST_CONTENT}}" >> .env.test

      - name: Run backend integration tests
        run: npm run test:backend:int

  e2e-tests:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v7.0.0
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/admin/package-lock.json

      - name: Create .env file
        run: echo "${{secrets.ENV_TEST_CONTENT}}" >> .env.test

      - name: Build containers and run tests
        run: npm run test:e2e:admin

      - name: Stop containers
        if: always()
        run: npm run posttest:e2e:admin
